---
title: "Data Import"
output: github_document
---

```{r echo = FALSE, message = FALSE}
library(tidyverse)
```


This document will show how to import data

## Import the FAS Litters CSV

janitor::clean_names calls the clean_names function from the janitor library without the need to load the janitor package.

```{r}
litters_df = read_csv("data/FAS_litters.csv")

litters_df = janitor::clean_names(litters_df)
```
## Look at teh dataset

```{r}
litters_df

head(litters_df)
tail(litters_df,10)
```


```{r eval = FALSE}
view(litters_df)
```

```{r}
pups_df = read_csv("data/FAS_pups.csv")
pups_df = janitor::clean_names(pups_df)
pups_df
```

## Look at read_csv options

column names
```{r}
litters_df=
  read.csv(
    file = "data/FAS_litters.csv"
                    # col_names = FALSE,
                    # skip = 2
  )
```

what about missing data
```{r}
litters_df=
  read.csv(
    file = "data/FAS_litters.csv",
    na = c(".", "NA", "")
  )

litters_df = janitor::clean_names(litters_df)
pull(litters_df, gd0_weight)
```

What if we code 'group' as a factor variable?
```{r}
litters_df = 
    read_csv(file = "./data/FAS_litters.csv",
        na = c(".", "NA", ""),
    col_types = cols(
      Group = col_factor()
    )
)
```

